import logging
import requests
import aiohttp
import asyncio
import math
from aiogram import Bot, Dispatcher, executor, types
from aiogram.contrib.middlewares.logging import LoggingMiddleware
from aiogram.types import Message
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton


API_TOKEN = '6173455658:AAGrQeUR51i4_4mm0sIvcxV-a_fwV1jK-Os'
# Configure logging
logging.basicConfig(level=logging.INFO)
# Initialize bot and dispatcher
bot = Bot(token=API_TOKEN)
dp = Dispatcher(bot)

# @dp.message_handler(commands='generate-3')
# async def gen(message: Message):
#     inputs = message.text.split()[1:]  # Split the message and get all inputs after the /gen command
#     if not inputs:
#         await bot.send_message(
#             chat_id=message.chat.id,
#             text=f'Hello {message.from_user.first_name}, Please enter the inputs after the /generate command',
#         )
#         return
    
#     await bot.send_message(
#         chat_id=message.chat.id,
#         text=f'Hi {message.from_user.first_name}!\n\nPrompts:\n({" ".join(inputs)})\n\n💋💋 I will be processing your image, please wait. 💋💋\n',
#     )
#     await requestApi(message, " ".join(inputs), 3)

# @dp.message_handler(commands='generate-2')
# async def gen(message: Message):
#     inputs = message.text.split()[1:]  # Split the message and get all inputs after the /gen command
#     if not inputs:
#         await bot.send_message(
#             chat_id=message.chat.id,
#             text=f'Hello {message.from_user.first_name}, Please enter the inputs after the /generate command',
#         )
#         return
    
#     await bot.send_message(
#         chat_id=message.chat.id,
#         text=f'Hi {message.from_user.first_name}!\n\nPrompts:\n({" ".join(inputs)})\n\n💋💋 I will be processing your image, please wait. 💋💋\n',
#     )
#     await requestApi(message, " ".join(inputs), 2)

@dp.message_handler(commands='start')
async def gen(message: Message):
    await bot.send_photo(
            chat_id=message.chat.id,
            caption=f'Hello {message.from_user.first_name}, I am AIGW_BOT, I can generate hyper-realistic NSFW images for you.\n\nPlease enter the postive prompts after the /generate_real command. \n\neg.\n`/generate_real 18 years old, blue eyes, teenager`\n\n',
            photo='https://i.ibb.co/R0Xmf2M/sss.png',
    )

@dp.message_handler(commands='generate_real')
async def gen(message: Message):
    inputs = message.text.split()[1:]  # Split the message and get all inputs after the /gen command
    if not inputs:
        await bot.send_message(
            chat_id=message.chat.id,
            text=f'Hello {message.from_user.first_name}, Please enter the inputs after the /generate command',
        )
        return
    
    await bot.send_message(
        chat_id=message.chat.id,
        text=f'Hi {message.from_user.first_name}!\n\nPrompts:\n({" ".join(inputs)})\n\n💋💋 I will be processing your image, please wait. 💋💋\n',
    )
    await requestApi(message, " ".join(inputs), 1)

async def send_image(message: Message, image_url: str, prompt: str, model: str):
    await bot.send_photo(
        chat_id=message.chat.id,
        caption=f'Here is your image, {message.from_user.first_name}!\nI hope you like it 💋.\n\nPROMPT:\n({prompt})\n\nModel: {model}\n\nGenerated by: {message.from_user.first_name}\n\n💋- AIGW_BOT -💋',
        photo=image_url,
    )
    
async def processing_update(message: Message, eta: int):
	await bot.send_message(
		chat_id=message.chat.id,
		text=f'Hi {message.from_user.first_name}!\n\nYour image is still being processed, Thank you for waiting. \n\nETA: {math.ceil(eta)} seconds.\n',
	)

async def error_update(message: Message):
	await bot.send_message(
		chat_id=message.chat.id,
		text=f'Hi {message.from_user.first_name}!\n\nDue to in-demand accesses and requests your image cannot be generated.\n\nPlease try again later.\n',
	)



async def requestApi(message, prompt, model):
    if model == 1:
        model = 'realistic-vision-v13'
    if model == 2:
        model = 'hassanblend-1512'
    if model == 3:
        model = 'protogen-3.4'
    url = 'https://stablediffusionapi.com/api/v3/dreambooth'
    headers = {
        'Content-Type': 'application/json'
    }
    payload = {
        'key': 'YimEHAg0HxDBkYtZp7X8ZEv7u84XWtt66TgVA78BnGWQlLHe6cdoDQREjpV5',
        'model_id': model,
        'prompt': prompt,
        'negative_prompt': 'painting, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, deformed, ugly, blurry, bad anatomy, bad proportions, extra limbs, cloned face, skinny, glitchy, double torso, extra arms, extra hands, mangled fingers, missing lips, ugly face, distorted face, extra legs, anime',
        'width': '512',
        'height': '512',
        'samples': '1',
        'num_inference_steps': '30',
        'seed': None,
        'guidance_scale': 7.5,
        'webhook': None,
        'track_id': None
    }
    
    while True:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers, json=payload) as resp:
                print('sent request')
                data = await resp.json()
                print(data)
                if resp.status == 200:
                    if data['status'] == 'processing' and data['messege'] == 'Request processing':
                        print('Requesting again')
                        requestApi(message, prompt, model)
                    if data['status'] == 'success':
                        await send_image(message, data['output'][0], prompt, model)
                        break
                    if data['status'] == 'processing':
                        if 'fetch_result' in data:
                            url = data['fetch_result']
                            eta = data['eta']
                        await processing_update(message, eta)
                        await asyncio.sleep(math.ceil(eta))
                        continue
                    if data['status'] == 'error':
                        await error_update(message)
                        break
                    if data['status'] == 'failed':
                        continue
                    else:
                        raise Exception(f'Request failed with status code {resp.status}')

dp.middleware.setup(LoggingMiddleware())
if __name__ == '__main__':
	executor.start_polling(dp, skip_updates=True )